spring:
  application:
    name: activityservice

  mongodb:
      uri: mongodb://localhost:27017/aiactivityfitness
      database: aiactivityfitness

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8082